FROM node:20 as build

WORKDIR /app

# Copy only package files first (cache optimization)
COPY app/package*.json ./
RUN npm install

# Copy the entire React/Vite project
COPY app/ .

# Build React app
RUN npm run build

# ---- Production image ----
FROM nginx:stable-alpine


# Remove default nginx content
RUN rm -rf /usr/share/nginx/html/*

# Copy built files to Nginx html directory
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80
CMD ["nginx", "-g", "daemon off;"]
