FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY frontend/yugantar/package*.json ./
RUN npm ci --legacy-peer-deps

# Expose dev port
EXPOSE 3000

# Mount code via volume in docker-compose
CMD ["npm", "start"]
